=== safeeulbashir/JAXBApp/src/main/resources/Student.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Student" xmlns:tns="http://www.example.org/Student" elementFormDefault="qualified">

    <complexType name="Student">
    	<sequence>
    		<element name="studentId" type="int" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="firstName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="lastName" type="string" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="marks" type="tns:marks" maxOccurs="1"
    			minOccurs="1">
    		</element>
    		<element name="addresses" type="tns:addresses" maxOccurs="1"
    			minOccurs="1">
    		</element>
    	</sequence>
    </complexType>
    
    <complexType name="address">
    	<sequence>
    		<element name="addressType" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="string">
    					<enumeration value="HOME"></enumeration>
    					<enumeration value="COMMUNICATION"></enumeration>
    				</restriction>
    			</simpleType>
    		</element>
    		<element name="line1" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="line2" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="city" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="state" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="zip" type="int" maxOccurs="1" minOccurs="1"></element>
    		<element name="country" type="string" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>
    
    <complexType name="addresses">
    	<sequence maxOccurs="2" minOccurs="1">
    		<element name="address" type="tns:address"></element>
    	</sequence>
    </complexType>

    <complexType name="mark">
    	<sequence>
    		<element name="subject" type="string" maxOccurs="1" minOccurs="1"></element>
    		<element name="mark" maxOccurs="1" minOccurs="1">
    			<simpleType>
    				<restriction base="int"></restriction>
    			</simpleType>
    		</element>
    		<element name="maxMark" type="int" maxOccurs="1" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="marks">
    	<sequence>
    		<element name="mark" type="tns:mark" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="Student" type="tns:Student"></element>
</schema>

=== safeeulbashir/JAXBApp/src/main/resources/Student.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Student xmlns:tns="http://www.example.org/Student"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Student student.xsd ">
	<tns:studentId>1</tns:studentId>
	<tns:firstName>Safeeul Bashir</tns:firstName>
	<tns:lastName>Safee</tns:lastName>
	<tns:marks>
		<tns:mark>
			<tns:subject>Java</tns:subject>
			<tns:mark>90</tns:mark>
			<tns:maxMark>100</tns:maxMark>
		</tns:mark>
		<tns:mark>
			<tns:subject>C++</tns:subject>
			<tns:mark>95</tns:mark>
			<tns:maxMark>100</tns:maxMark>
		</tns:mark>
	</tns:marks>
	<tns:addresses>
		<tns:address>
			<tns:addressType>HOME</tns:addressType>
			<tns:line1>1026 San Jacinto Dr.</tns:line1>
			<tns:line2>Apt 1026</tns:line2>
			<tns:city>Irving</tns:city>
			<tns:state>Tx</tns:state>
			<tns:zip>75063</tns:zip>
			<tns:country>USA</tns:country>
		</tns:address>
	</tns:addresses>
</tns:Student>
